services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      DB_URL: "root:12345@tcp(db:3306)/ledger_app?parseTime=true"
    restart: always

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: ledger_app
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data: